/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.simpleblog.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Author service. Represents a row in the &quot;SimpleBlog_Author&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.simpleblog.model.impl.AuthorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.simpleblog.model.impl.AuthorImpl}.
 * </p>
 *
 * @author jbloggs
 * @see Author
 * @see com.liferay.portlet.simpleblog.model.impl.AuthorImpl
 * @see com.liferay.portlet.simpleblog.model.impl.AuthorModelImpl
 * @generated
 */
public interface AuthorModel extends BaseModel<Author>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a author model instance should use the {@link Author} interface instead.
	 */

	/**
	 * Returns the primary key of this author.
	 *
	 * @return the primary key of this author
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this author.
	 *
	 * @param primaryKey the primary key of this author
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the author ID of this author.
	 *
	 * @return the author ID of this author
	 */
	public long getAuthorId();

	/**
	 * Sets the author ID of this author.
	 *
	 * @param authorId the author ID of this author
	 */
	public void setAuthorId(long authorId);

	/**
	 * Returns the company ID of this author.
	 *
	 * @return the company ID of this author
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this author.
	 *
	 * @param companyId the company ID of this author
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this author.
	 *
	 * @return the group ID of this author
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this author.
	 *
	 * @param groupId the group ID of this author
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this author.
	 *
	 * @return the user ID of this author
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this author.
	 *
	 * @param userId the user ID of this author
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this author.
	 *
	 * @return the user uuid of this author
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this author.
	 *
	 * @param userUuid the user uuid of this author
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this author.
	 *
	 * @return the user name of this author
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this author.
	 *
	 * @param userName the user name of this author
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this author.
	 *
	 * @return the create date of this author
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this author.
	 *
	 * @param createDate the create date of this author
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this author.
	 *
	 * @return the modified date of this author
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this author.
	 *
	 * @param modifiedDate the modified date of this author
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this author.
	 *
	 * @return the name of this author
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this author.
	 *
	 * @param name the name of this author
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(Author author);

	public int hashCode();

	public CacheModel<Author> toCacheModel();

	public Author toEscapedModel();

	public String toString();

	public String toXmlString();
}